In [2]:
import numpy as np

In [102]:
data1 = [6,7.5,8,0,1]
data1

[6, 7.5, 8, 0, 1]

In [103]:
# numpy를 이용하여 1차원 1배열로 변형하기
arr1 = np.array(data1)
arr1 

array([6. , 7.5, 8. , 0. , 1. ])

In [104]:
# 배열의 크기 확인하기
arr1.shape

(5,)

### 2차원

In [105]:
data2 = [
    [1,2,3,4],
    [5,6,7,8]
]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [106]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
arr2.shape  #(2, 4) = 2행, 4열

(2, 4)

In [108]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [109]:
# 0으로 구성된 5행 2열의 3차원 배열 생성
np.zeros([4, 5, 2])
    # 4페이지, 5행, 2열

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [110]:
# 1로만 구성된 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [111]:
# 10으로 구성된 배열 생성
np.full(5, 10)  # 10이 5개

array([10, 10, 10, 10, 10])

In [112]:
# 0으로 구성된 3행 5열 배열 생성
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
np.full((3,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [114]:
# 범위가 있는 배열
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [115]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [116]:
# 정수형으로 이루어진 배열 -> 실수형으로 변환
# dtype 안주면 default: 실수
arr = np.array([1,2,3,4,5], dtype=np.int64)
arr.dtype

dtype('int64')

In [117]:
float_arr = arr.astype(np.float64)
float_arr
float_arr.dtype

dtype('float64')

### 행렬 연산

In [118]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [120]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [121]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [122]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [123]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [124]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [125]:
1 / arr1    # 역수

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [126]:
(1 / arr1) * arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [127]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
arr[5]

5

In [129]:
arr[5:9]

array([5, 6, 7, 8])

In [130]:
# 손상된 이미지를 복원할 때 사용
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [131]:
arr[:5]

array([0, 1, 2, 3, 4])

In [132]:
arr[8:]

array([12,  9])

### 2차원 배열

In [133]:
# 대괄호 2개
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [134]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [135]:
# 1에서 2번행의 자료 출력
# arr2d[(1,2),:]
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
# 0,1열의 자료 출력
arr2d[:,range(0,2)]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [137]:
# 1행2열의 자료 출력
arr2d[1,2]

7

In [138]:
arr2d[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [139]:
# 차원 축소
arr2d[0:2,1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 차원 축소(미분)
- General Performance
- Train: train valid data
    - 과대 적합: 예측률이 높고 train data에 너무 맞춰져 있다. train 데이터 예측력이 훨씬 더 높다
    - 과소 적합: Test 예측률이 train 예측률보다 훨씬 더 높다.
- Test

- 0차원: ex) int a = 1
- 1차원: ex) 배열 [1,2,3..]
    > 적분


### 난수 발생 (시뮬레이션)
- rand : 0~1사이의 균일 분포
- randn : 가우시안 표준 정규 분포 (벨 뒤집은 모양 그래프에서 중간에 있는 데이터가 가장 많이 나옴, 가운데시안)
- randint: 균일분포의 정수 난수

In [140]:
names = np.array([
    "Charles",
    "Kenny",
    "Hayoung",
    "Charles",
    "Hayoung",
    "Kenny",
    "Kenny"
])

data = np.random.randn(7,4)

In [141]:
data

array([[-0.22396828, -0.90648719,  0.79078218, -1.55078491],
       [-0.08234071, -0.79205866,  0.05478992,  1.99721382],
       [-0.03454453,  0.45747619, -1.45481805, -0.01551393],
       [-0.35740193, -1.62972717, -0.88791518, -0.79478211],
       [-0.32706949,  0.8053498 , -0.32013542, -1.20470985],
       [ 0.07793044, -0.52648486,  0.10283066, -0.42596849],
       [-1.92022339, -0.17574997,  0.8711992 ,  0.3871717 ]])

In [142]:
# Mask
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [143]:
data[names == 'Charles', :] #True에 해당하는 행 출력

array([[-0.22396828, -0.90648719,  0.79078218, -1.55078491],
       [-0.35740193, -1.62972717, -0.88791518, -0.79478211]])

In [144]:
data[(names == 'Charles') | (names == "Kenny"), :]

array([[-0.22396828, -0.90648719,  0.79078218, -1.55078491],
       [-0.08234071, -0.79205866,  0.05478992,  1.99721382],
       [-0.35740193, -1.62972717, -0.88791518, -0.79478211],
       [ 0.07793044, -0.52648486,  0.10283066, -0.42596849],
       [-1.92022339, -0.17574997,  0.8711992 ,  0.3871717 ]])

In [145]:
# data의 4번째 열 값 중 0보다 작은 것의 mask 만들기
data[:,3] < 0

array([ True, False,  True,  True,  True,  True, False])

In [146]:
data[data[:,3] < 0, 0]

array([-0.22396828, -0.03454453, -0.35740193, -0.32706949,  0.07793044])

In [147]:
# 차원 축소
data[data[:,3] < 0, 0] = 0
data

array([[ 0.        , -0.90648719,  0.79078218, -1.55078491],
       [-0.08234071, -0.79205866,  0.05478992,  1.99721382],
       [ 0.        ,  0.45747619, -1.45481805, -0.01551393],
       [ 0.        , -1.62972717, -0.88791518, -0.79478211],
       [ 0.        ,  0.8053498 , -0.32013542, -1.20470985],
       [ 0.        , -0.52648486,  0.10283066, -0.42596849],
       [-1.92022339, -0.17574997,  0.8711992 ,  0.3871717 ]])

In [148]:
# 정렬
arr = np.random.rand(8)
arr

array([0.08534049, 0.77753404, 0.26115898, 0.23968995, 0.94197517,
       0.20230467, 0.84116104, 0.0386544 ])

In [149]:
# 오름차순
np.sort(arr)

array([0.0386544 , 0.08534049, 0.20230467, 0.23968995, 0.26115898,
       0.77753404, 0.84116104, 0.94197517])

In [150]:
# 내림차순
np.sort(arr)[::-1]

array([0.94197517, 0.84116104, 0.77753404, 0.26115898, 0.23968995,
       0.20230467, 0.08534049, 0.0386544 ])

In [151]:
arr = np.random.rand(5, 3)
arr

array([[0.74314602, 0.75813949, 0.21160689],
       [0.52793665, 0.24619053, 0.45979036],
       [0.67270953, 0.98637092, 0.71748466],
       [0.77247727, 0.9735833 , 0.38645963],
       [0.29242241, 0.28209131, 0.5747065 ]])

In [152]:
# 열방향(열 기준) 오름 차순
np.sort(arr, axis=0)

array([[0.29242241, 0.24619053, 0.21160689],
       [0.52793665, 0.28209131, 0.38645963],
       [0.67270953, 0.75813949, 0.45979036],
       [0.74314602, 0.9735833 , 0.5747065 ],
       [0.77247727, 0.98637092, 0.71748466]])

In [153]:
# 행방향 오름차순
np.sort(arr, axis=1)

array([[0.21160689, 0.74314602, 0.75813949],
       [0.24619053, 0.45979036, 0.52793665],
       [0.67270953, 0.71748466, 0.98637092],
       [0.38645963, 0.77247727, 0.9735833 ],
       [0.28209131, 0.29242241, 0.5747065 ]])

---
## reshape
- 차원 바꿈

In [154]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [155]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2, 4))  # 2행 4열
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [156]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, (2,2,2))     #(page, row, column)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [157]:
# 2차원 배열을 1차원(column 1개, row 여러 개)으로 변경
# -1은 데이터의 개수를 정할 수 없는 경우에 쓴다.
# arr3 = arr1.reshape(-1) #분석용
arr3 = arr1.reshape(-1, 1)  # 딥러닝 할 때 1 있어야 됨
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [158]:
arr4 = arr1.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [159]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [166]:
# 3차원 배열을 1차원으로 변경
arr5 = arr2.reshape(-1, 1)  # 1은 차원을 표시하기 위함
arr5

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [161]:
arr3 == arr5

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])